Added validation set
LHTcode/Violence-detection pull request #1
Opened 2022-07-16 15:23 UTC by Qwer1234fgdgeg

2022-07-16 15:36 UTC, LHTcode commented on model/R3D.py
> +            # if not os.path.exists(save_model_path):  # 如果没有这个目录就创建
这里为什么要注释阿，还有把print去掉

2022-07-16 15:37 UTC, LHTcode commented on tools/train.py
>  print(sys.modules)
把print去掉把

2022-07-16 15:37 UTC, LHTcode commented on tools/train.py
> +    train_model = R3D_18('root_path', pretrained=False)  # 使用训练好的参数作为初始化参数
为啥要加引号阿，加引号不就变成了字符串

2022-07-16 15:42 UTC, LHTcode commented on tools/train.py
> +sys.path.append(base)
不要写在 import 的中间

2022-07-16 15:44 UTC, LHTcode commented on tools/valid.py
> +base = os.path.abspath("../")
不要写在 import 的中间

2022-07-16 15:44 UTC, LHTcode commented on tools/valid.py
> +sys.path.append(base)
这两行不要写在 import 的中间

2022-07-16 15:48 UTC, LHTcode commented on tools/valid.py
> +sys.path.append(base)
这两行不要写在 import 中间

2022-07-19 03:54 UTC, LHTcode commented
还有很多东西没解决。

2022-07-20 07:41 UTC, LHTcode commented
我上面那个review那里你还有很多东西没修改的呀，绝对地址、Summarywriter那些。

2022-07-20 07:42 UTC, LHTcode commented
你最新的commit就只是加了几个空格和回车 @Qwer1234fgdgeg

2022-07-20 07:47 UTC, LHTcode commented
你可以下载个手机邮箱，可以直接在邮件里面回复。**另外**，review 指的是这个：
![review截图](https://user-images.githubusercontent.com/75188358/179926413-2e42ebe8-9feb-4dca-9034-9583cb141a1c.png)

2022-07-20 13:00 UTC, Qwer1234fgdgeg commented
> 

SummaryWriter有什么要改的

2022-07-20 13:10 UTC, LHTcode commented
> > 
> 
> SummaryWriter有什么要改的

你的 valid 里面没写SummaryWirter吧，你要添加一个。

2022-07-20 13:13 UTC, LHTcode commented
> > > 
> > 
> > 
> > SummaryWriter有什么要改的
> 
> 你的 valid 里面没写SummaryWirter吧，你要添加一个。

你如果不知道 SummaryWriter 是啥你就先去查查，然后看看我的 train 里面是怎么写的，参考一下。

2022-07-20 14:20 UTC, Qwer1234fgdgeg commented
> 我上面那个review那里你还有很多东西没修改的呀，绝对地址、Summarywriter那些。

2022-07-20 14:21 UTC, Qwer1234fgdgeg commented
我全部review看了一次了，还有什么漏了吗

2022-07-20 14:24 UTC, LHTcode commented
你怎么把pr关了hhh



---- Replied Message ----
| From | ***@***.***> |
| Date | 07/20/2022 22:20 |
| To | ***@***.***> |
| Cc | ***@***.***>、State ***@***.***> |
| Subject | Re: [LHTcode/Violence-detection] Added validation set (PR #1) |

Closed #1.

—
Reply to this email directly, view it on GitHub, or unsubscribe.
You are receiving this because you modified the open/close state.Message ID: ***@***.***>

2022-07-20 14:25 UTC, LHTcode commented
那个summarywriter写错了，你看看我的review那里新的评论



---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2022年07月20日 22:21 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.***>、State ***@***.***> |
| 主题 | Re: [LHTcode/Violence-detection] Added validation set (PR #1) |

我全部review看了一次了，还有什么漏了吗

—
Reply to this email directly, view it on GitHub, or unsubscribe.
You are receiving this because you modified the open/close state.Message ID: ***@***.***>

2022-07-20 14:37 UTC, Qwer1234fgdgeg commented
我尝试了一下，结果不会开了

2022-07-20 14:43 UTC, Qwer1234fgdgeg commented
我怎么找不到valid的review

2022-07-21 12:01 UTC, LHTcode requested changes

2022-07-21 12:01 UTC, LHTcode commented on tools/valid.py
> +sys.path.append(base)
这两行不要写在 import 中间，而且跟下面的 root_path 重复了，简化一下

2022-07-21 12:01 UTC, LHTcode commented on tools/valid.py
> +    model_path = root_path+"./models_parameters/2022.7.16/best_model.pt"
去掉绝对地址，不要出现斜杠

2022-07-21 12:01 UTC, LHTcode commented on tools/valid.py
> +    print("模型加载完成")
不要 print 中文信息

2022-07-21 12:01 UTC, LHTcode commented on tools/valid.py
> +        target = torch.tensor(target).to(torch.long).to(device)
data 返回的 target 就是 tensor，并且不用 .to() 一大堆东西。

2022-07-21 12:01 UTC, LHTcode commented on tools/valid.py
> +        print("预测",preds)
不要 print 一些调试信息，并且不要出现中文，要 print 的最关键信息是 precision

2022-07-21 12:01 UTC, LHTcode commented on tools/valid.py
> +    print(root_path)
不要 print 调试信息。
**另外，解决完所有的问题之后在本地跑一边，ok了再 commit 上来。**

2022-07-21 12:01 UTC, LHTcode commented on tools/valid.py
> +from torch.utils.tensorboard import SummaryWriter
你怎么没用到 SummaryWriter ？我要记录精度信息的呀，你把它写进 valid 函数的参数里面，参考一下我的 train 是咋写的。

2022-07-21 12:01 UTC, LHTcode commented on tools/valid.py
> +    writer = SummaryWriter(log_dir=os.path.join(root_path, "exact_log", local_time_dir))
错了错了，这是 wirter 的初始化而已，writer的初始化不应该放在这。并且，log_dir 用我train里面写的那个地址。

2022-07-22 03:48 UTC, Qwer1234fgdgeg commented
记录精度要加上epoch吗

2022-07-22 06:49 UTC, LHTcode commented
> 记录精度要加上epoch吗

要的

2022-07-23 03:48 UTC, LHTcode commented
@Qwer1234fgdgeg 快改

2022-07-23 08:17 UTC, Qwer1234fgdgeg commented
好好好，回去马上改

2022-07-23 14:48 UTC, LHTcode commented
看了一下，大概ok了

2022-07-23 14:48 UTC, LHTcode approved these changes

2022-07-23 14:50 UTC, merged